# Generated by Django 4.2.7 on 2023-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='seasonImage',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Images/Seasons/'),
        ),
    ]
