# Generated by Django 4.2.7 on 2023-11-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seasons', '0003_season_seasoncontactphonenumber_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='seasonDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='seasonLocation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='seasonContactPhoneNumber_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='seasonContactPhoneNumber_2',
            field=models.IntegerField(null=True),
        ),
    ]
