# Generated by Django 4.2.7 on 2023-11-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seasons', '0005_season_seasonspeaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='seasonContactPhoneNumber_1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='seasonContactPhoneNumber_2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
