# Generated by Django 4.2.7 on 2023-11-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectDetails', models.CharField(max_length=10000)),
                ('projectMemebers', models.CharField(max_length=1000)),
                ('projectRating', models.SmallIntegerField()),
            ],
        ),
    ]
