# Generated by Django 4.2.7 on 2023-11-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventModule', '0003_alter_projectpost_projectmemebers'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventImage',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Images/events/'),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='projectImage',
            field=models.FileField(default=True, max_length=250, null=True, upload_to='Images/project/'),
        ),
    ]
